#ifndef TARANTOOL_SQL_STATS_ANALYZE_BUDGET_H
#define TARANTOOL_SQL_STATS_ANALYZE_BUDGET_H

#include <stdint.h>

/*
 * Fixed initial ceilings for volatile ANALYZE. These are deliberately not
 * SQL/session settings: one command either completes within every aggregate
 * bound or fails without publishing a candidate.
 */
#define SQL_STATS_ANALYZE_MAX_INDEX_REQUESTS 256
#define SQL_STATS_ANALYZE_MAX_SAMPLE_ROWS 1024
#define SQL_STATS_ANALYZE_MAX_SAMPLE_BYTES (4U * 1024U * 1024U)
#define SQL_STATS_ANALYZE_MAX_RESERVOIR_BYTES (8U * 1024U * 1024U)
#define SQL_STATS_ANALYZE_MAX_TUPLES_EXAMINED UINT64_C(1000000)
#define SQL_STATS_ANALYZE_MAX_DISK_SOURCES UINT64_C(65536)
#define SQL_STATS_ANALYZE_MAX_PAGE_READS UINT64_C(262144)
#define SQL_STATS_ANALYZE_MAX_ITERATOR_KEYS UINT64_C(1000000)
#define SQL_STATS_ANALYZE_MAX_STAGING_BYTES (64U * 1024U * 1024U)
#define SQL_STATS_ANALYZE_MAX_CANDIDATE_BYTES (64U * 1024U * 1024U)
#define SQL_STATS_ANALYZE_MAX_TEMP_BYTES (16U * 1024U * 1024U)
#define SQL_STATS_ANALYZE_MAX_WORK UINT64_C(100000000)
#define SQL_STATS_ANALYZE_INDEX_SUMMARY_BYTES (1024U * 1024U)
#define SQL_STATS_ANALYZE_HLL_PRECISION 10

#endif /* TARANTOOL_SQL_STATS_ANALYZE_BUDGET_H */
