test_run = require('test_run').new()
engine = test_run:get_cfg('engine')
_ = box.space._session_settings:update('sql_default_engine', {{'=', 2, engine}})

box.execute([[SET SESSION "sql_new_planner_single_table" = true]])
before = box.stat.sql()
summary, err = box.execute([[EXPLAIN (planner = 'summary') WITH RECURSIVE cnt(x) AS (VALUES(1) UNION ALL SELECT x+1 FROM cnt WHERE x<3) SELECT x FROM cnt]])
assert(err == nil)
assert(summary.rows[1][1] == 'planner')
assert(summary.rows[1][2] == 'path_class')
assert(summary.rows[1][3] == 'fallback')
assert(summary.rows[2][2] == 'fallback_reason')
assert(summary.rows[2][3] == 'UNSUPPORTED_CTE')
after = box.stat.sql()
assert(after.sql_planner_fallback_total == before.sql_planner_fallback_total + 1)
assert(after.sql_planner_fallback_UNSUPPORTED_CTE_total == before.sql_planner_fallback_UNSUPPORTED_CTE_total + 1)
box.execute([[SET SESSION "sql_new_planner_single_table" = false]])
test_run = require('test_run').new()
