test_run = require('test_run').new()
engine = test_run:get_cfg('engine')
_ = box.space._session_settings:update('sql_default_engine', {{'=', 2, engine}})
box.execute([[SET SESSION "sql_seq_scan" = true;]])

box.execute([[CREATE TABLE planner_preflight_t (id INTEGER PRIMARY KEY, v INTEGER)]])
box.execute([[INSERT INTO planner_preflight_t VALUES (1, 10), (2, 20), (3, NULL)]])

summary, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_t]])
assert(err == nil and summary.rows[1][3] == 'fallback')
box.execute([[SET SESSION "sql_new_planner_single_table" = true]])
plain_result, plain_error = box.execute([[SELECT v FROM planner_preflight_t]])
assert(plain_error == nil)
assert(plain_result.rows[1][1] == 10)
assert(plain_result.rows[2][1] == 20)
assert(plain_result.rows[3][1] == box.NULL)
projected_result, projected_error = box.execute([[SELECT id, v FROM planner_preflight_t]])
assert(projected_error == nil)
assert(#projected_result.rows == 3)
assert(projected_result.rows[1][1] == 1 and projected_result.rows[1][2] == 10)
assert(projected_result.rows[3][1] == 3 and projected_result.rows[3][2] == box.NULL)
limited_result, limited_error = box.execute([[SELECT v FROM planner_preflight_t LIMIT 1]])
assert(limited_error == nil and #limited_result.rows == 1)
assert(limited_result.rows[1][1] == 10)
empty_limit_result, empty_limit_error = box.execute([[SELECT v FROM planner_preflight_t LIMIT 0]])
assert(empty_limit_error == nil and #empty_limit_result.rows == 0)
offset_result, offset_error = box.execute([[SELECT v FROM planner_preflight_t LIMIT 1 OFFSET 1]])
assert(offset_error == nil and #offset_result.rows == 1 and offset_result.rows[1][1] == 20)
ordered_result, ordered_error = box.execute([[SELECT v FROM planner_preflight_t ORDER BY id DESC LIMIT 1]])
assert(ordered_error == nil and #ordered_result.rows == 1 and ordered_result.rows[1][1] == box.NULL)
summary, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_t]])
assert(err == nil)
assert(summary.rows[1][3] == 'new_planner')
summary, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_t LIMIT 1]])
assert(err == nil and summary.rows[1][3] == 'new_planner')
summary, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_t LIMIT 1 OFFSET 1]])
assert(err == nil and summary.rows[1][3] == 'new_planner')
summary, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_t ORDER BY id DESC LIMIT 1]])
assert(err == nil and summary.rows[1][3] == 'new_planner')
summary, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_t ORDER BY v]])
assert(err == nil and summary.rows[1][3] == 'fallback')
summary, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_t LIMIT 2147483648]])
assert(err == nil and summary.rows[1][3] == 'fallback')
wide_limit_result, wide_limit_error = box.execute([[SELECT v FROM planner_preflight_t LIMIT 2147483648]])
assert(wide_limit_error == nil and #wide_limit_result.rows == 3)
filter_fallback_before = box.stat.sql()
filter_summary, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_t WHERE id = 2]])
assert(err == nil and filter_summary.rows[1][3] == 'fallback')
assert(filter_summary.rows[2][3] == 'UNSUPPORTED_FILTER', tostring(filter_summary.rows[2][3]))
filter_fallback_after = box.stat.sql()
assert(filter_fallback_after.sql_planner_fallback_total == filter_fallback_before.sql_planner_fallback_total + 1)
assert(filter_fallback_after.sql_planner_fallback_UNSUPPORTED_FILTER_total == filter_fallback_before.sql_planner_fallback_UNSUPPORTED_FILTER_total + 1)

filtered = box.execute([[SELECT v FROM planner_preflight_t WHERE id = 2]])
assert(#filtered.rows == 1 and filtered.rows[1][1] == 20)
computed_result, computed_error = box.execute([[SELECT v + 1 FROM planner_preflight_t]])
assert(computed_error == nil)
assert(computed_result.rows[1][1] == 11 and computed_result.rows[2][1] == 21)

box.execute([[CREATE TABLE planner_preflight_empty_t (id INTEGER PRIMARY KEY, v INTEGER)]])
empty_result, empty_error = box.execute([[SELECT v FROM planner_preflight_empty_t]])
assert(empty_error == nil and #empty_result.rows == 0)
box.execute([[DROP TABLE planner_preflight_empty_t]])

box.execute([[SET SESSION "sql_new_planner_single_table" = false]])
summary, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_t]])
assert(err == nil and summary.rows[1][3] == 'fallback')

box.execute([[DROP TABLE planner_preflight_t]])
test_run = require('test_run').new()
