test_run = require('test_run').new()
engine = test_run:get_cfg('engine')
_ = box.space._session_settings:update('sql_default_engine', {{'=', 2, engine}})

box.execute([[CREATE TABLE fallback_collation_t (id INTEGER PRIMARY KEY, v STRING)]])
before = box.stat.sql()
summary, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v COLLATE "unicode_ci" FROM fallback_collation_t]])
assert(err == nil)
assert(summary.rows[1][3] == 'fallback')
assert(summary.rows[2][3] == 'UNSUPPORTED_COLLATION')
after = box.stat.sql()
assert(after.sql_planner_fallback_total == before.sql_planner_fallback_total + 1)
assert(after.sql_planner_fallback_UNSUPPORTED_COLLATION_total == before.sql_planner_fallback_UNSUPPORTED_COLLATION_total + 1)
test_run = require('test_run').new()
