test_run = require('test_run').new()
engine = test_run:get_cfg('engine')
_ = box.space._session_settings:update('sql_default_engine', {{'=', 2, engine}})
box.execute([[SET SESSION "sql_seq_scan" = true;]])

box.execute([[CREATE TABLE planner_preflight_t (id INTEGER PRIMARY KEY, v INTEGER)]])
box.execute([[INSERT INTO planner_preflight_t VALUES (1, 10), (2, 20), (3, NULL)]])

summary, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_t]])
assert(err == nil and summary.rows[1][3] == 'fallback')
point_default_summary, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_t WHERE id = 2]])
assert(err == nil and point_default_summary.rows[1][3] == 'fallback')
box.execute([[SET SESSION "sql_new_planner_single_table" = true]])
plain_result, plain_error = box.execute([[SELECT v FROM planner_preflight_t]])
assert(plain_error == nil)
assert(plain_result.rows[1][1] == 10)
assert(plain_result.rows[2][1] == 20)
assert(plain_result.rows[3][1] == box.NULL)
projected_result, projected_error = box.execute([[SELECT id, v FROM planner_preflight_t]])
assert(projected_error == nil)
assert(#projected_result.rows == 3)
assert(projected_result.rows[1][1] == 1 and projected_result.rows[1][2] == 10)
assert(projected_result.rows[3][1] == 3 and projected_result.rows[3][2] == box.NULL)
limited_result, limited_error = box.execute([[SELECT v FROM planner_preflight_t LIMIT 1]])
assert(limited_error == nil and #limited_result.rows == 1)
assert(limited_result.rows[1][1] == 10)
empty_limit_result, empty_limit_error = box.execute([[SELECT v FROM planner_preflight_t LIMIT 0]])
assert(empty_limit_error == nil and #empty_limit_result.rows == 0)
offset_result, offset_error = box.execute([[SELECT v FROM planner_preflight_t LIMIT 1 OFFSET 1]])
assert(offset_error == nil and #offset_result.rows == 1 and offset_result.rows[1][1] == 20)
ordered_result, ordered_error = box.execute([[SELECT v FROM planner_preflight_t ORDER BY id DESC LIMIT 1]])
assert(ordered_error == nil and #ordered_result.rows == 1 and ordered_result.rows[1][1] == box.NULL)
summary, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_t]])
assert(err == nil)
assert(summary.rows[1][3] == 'new_planner')
summary, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_t LIMIT 1]])
assert(err == nil and summary.rows[1][3] == 'new_planner')
summary, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_t LIMIT 1 OFFSET 1]])
assert(err == nil and summary.rows[1][3] == 'new_planner')
summary, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_t ORDER BY id DESC LIMIT 1]])
assert(err == nil and summary.rows[1][3] == 'new_planner')
summary, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_t ORDER BY v]])
assert(err == nil and summary.rows[1][3] == 'fallback')
summary, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_t LIMIT 2147483648]])
assert(err == nil and summary.rows[1][3] == 'new_planner')
wide_limit_result, wide_limit_error = box.execute([[SELECT v FROM planner_preflight_t LIMIT 2147483648]])
assert(wide_limit_error == nil and #wide_limit_result.rows == 3)
wide_limit_offset_result, wide_limit_offset_error = box.execute([[SELECT v FROM planner_preflight_t LIMIT 2147483648 OFFSET 2147483649]])
assert(wide_limit_offset_error == nil and #wide_limit_offset_result.rows == 0)
summary, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_t LIMIT 2147483648 OFFSET 2147483649]])
assert(err == nil and summary.rows[1][3] == 'new_planner')
max_limit_offset_result, max_limit_offset_error = box.execute([[SELECT v FROM planner_preflight_t LIMIT 9223372036854775807 OFFSET 9223372036854775806]])
assert(max_limit_offset_error == nil and #max_limit_offset_result.rows == 0)
summary, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_t LIMIT 9223372036854775807 OFFSET 9223372036854775806]])
assert(err == nil and summary.rows[1][3] == 'new_planner')
filter_fallback_before = box.stat.sql()
filter_summary, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_t WHERE id = 2]])
assert(err == nil and filter_summary.rows[1][3] == 'new_planner')
filter_fallback_after = box.stat.sql()
assert(filter_fallback_after.sql_planner_fallback_total == filter_fallback_before.sql_planner_fallback_total)

filtered = box.execute([[SELECT v FROM planner_preflight_t WHERE id = 2]])
assert(#filtered.rows == 1 and filtered.rows[1][1] == 20)
reversed_point, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_t WHERE 2 = id]])
assert(err == nil and reversed_point.rows[1][3] == 'new_planner')
reversed_point_result = box.execute([[SELECT v FROM planner_preflight_t WHERE 2 = id]])
assert(#reversed_point_result.rows == 1 and reversed_point_result.rows[1][1] == 20)
limited_point_summary, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_t WHERE id = 2 LIMIT 1]])
assert(err == nil and limited_point_summary.rows[1][3] == 'new_planner')
limited_point = box.execute([[SELECT v FROM planner_preflight_t WHERE id = 2 LIMIT 1]])
assert(#limited_point.rows == 1 and limited_point.rows[1][1] == 20)
ordered_point_summary, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_t WHERE id = 2 ORDER BY id DESC]])
assert(err == nil and ordered_point_summary.rows[1][3] == 'new_planner')
ordered_point = box.execute([[SELECT v FROM planner_preflight_t WHERE id = 2 ORDER BY id DESC]])
assert(#ordered_point.rows == 1 and ordered_point.rows[1][1] == 20)
zero_limited_point = box.execute([[SELECT v FROM planner_preflight_t WHERE id = 2 LIMIT 0]])
assert(#zero_limited_point.rows == 0)
offset_point = box.execute([[SELECT v FROM planner_preflight_t WHERE id = 2 LIMIT 1 OFFSET 1]])
assert(#offset_point.rows == 0)
point_miss = box.execute([[SELECT v FROM planner_preflight_t WHERE id = 99]])
assert(#point_miss.rows == 0)
negative_point = box.execute([[SELECT v FROM planner_preflight_t WHERE id = -1]])
assert(#negative_point.rows == 0)
negative_point_summary, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_t WHERE id = -1]])
assert(err == nil and negative_point_summary.rows[1][3] == 'new_planner')
unsupported_range, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_t WHERE id > 1]])
assert(err == nil and unsupported_range.rows[1][3] == 'fallback')
assert(unsupported_range.rows[2][3] == 'UNSUPPORTED_FILTER')
bound_point, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_t WHERE id = ?]], {2})
assert(err == nil and bound_point.rows[1][3] == 'fallback')
assert(bound_point.rows[2][3] == 'UNSUPPORTED_FILTER')
bound_point_result = box.execute([[SELECT v FROM planner_preflight_t WHERE id = ?]], {2})
assert(#bound_point_result.rows == 1 and bound_point_result.rows[1][1] == 20)
non_primary_point, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_t WHERE v = 20]])
assert(err == nil and non_primary_point.rows[1][3] == 'fallback')
assert(non_primary_point.rows[2][3] == 'UNSUPPORTED_FILTER')
non_primary_point_result = box.execute([[SELECT v FROM planner_preflight_t WHERE v = 20]])
assert(#non_primary_point_result.rows == 1 and non_primary_point_result.rows[1][1] == 20)
compound_filter, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_t WHERE id = 1 OR id = 2]])
assert(err == nil and compound_filter.rows[1][3] == 'fallback')
assert(compound_filter.rows[2][3] == 'UNSUPPORTED_FILTER')
compound_filter_result = box.execute([[SELECT v FROM planner_preflight_t WHERE id = 1 OR id = 2]])
assert(#compound_filter_result.rows == 2)
null_point, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_t WHERE id = NULL]])
assert(err == nil and null_point.rows[1][3] == 'fallback')
assert(null_point.rows[2][3] == 'UNSUPPORTED_FILTER')
null_point_result = box.execute([[SELECT v FROM planner_preflight_t WHERE id = NULL]])
assert(#null_point_result.rows == 0)
computed_point, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_t WHERE id = 1 + 1]])
assert(err == nil and computed_point.rows[1][3] == 'fallback')
assert(computed_point.rows[2][3] == 'UNSUPPORTED_FILTER')
computed_point_result = box.execute([[SELECT v FROM planner_preflight_t WHERE id = 1 + 1]])
assert(#computed_point_result.rows == 1 and computed_point_result.rows[1][1] == 20)
computed_result, computed_error = box.execute([[SELECT v + 1 FROM planner_preflight_t]])
assert(computed_error == nil)
assert(computed_result.rows[1][1] == 11 and computed_result.rows[2][1] == 21)

box.execute([[CREATE TABLE planner_preflight_empty_t (id INTEGER PRIMARY KEY, v INTEGER)]])
empty_result, empty_error = box.execute([[SELECT v FROM planner_preflight_empty_t]])
assert(empty_error == nil and #empty_result.rows == 0)
box.execute([[DROP TABLE planner_preflight_empty_t]])

box.execute([[CREATE TABLE planner_preflight_wide_t (id INTEGER PRIMARY KEY, v INTEGER)]])
box.execute([[INSERT INTO planner_preflight_wide_t VALUES (9223372036854775807, 7), (-9223372036854775808, 8)]])
wide_point_summary, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_wide_t WHERE id = 9223372036854775807]])
assert(err == nil and wide_point_summary.rows[1][3] == 'new_planner')
wide_point = box.execute([[SELECT v FROM planner_preflight_wide_t WHERE id = 9223372036854775807]])
assert(#wide_point.rows == 1 and wide_point.rows[1][1] == 7)
wide_negative_point_summary, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_wide_t WHERE id = -9223372036854775808]])
assert(err == nil and wide_negative_point_summary.rows[1][3] == 'new_planner')
wide_negative_point = box.execute([[SELECT v FROM planner_preflight_wide_t WHERE id = -9223372036854775808]])
assert(#wide_negative_point.rows == 1 and wide_negative_point.rows[1][1] == 8)
box.execute([[DROP TABLE planner_preflight_wide_t]])

box.execute([[CREATE TABLE planner_preflight_unsigned_t (id UNSIGNED PRIMARY KEY, v INTEGER)]])
box.execute([[INSERT INTO planner_preflight_unsigned_t VALUES (9223372036854775807, 9)]])
box.execute([[INSERT INTO planner_preflight_unsigned_t VALUES (18446744073709551615, 10)]])
unsigned_point_summary, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_unsigned_t WHERE id = 9223372036854775807]])
assert(err == nil and unsigned_point_summary.rows[1][3] == 'new_planner')
unsigned_point = box.execute([[SELECT v FROM planner_preflight_unsigned_t WHERE id = 9223372036854775807]])
assert(#unsigned_point.rows == 1 and unsigned_point.rows[1][1] == 9)
unsigned_max_point_summary, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_unsigned_t WHERE id = 18446744073709551615]])
assert(err == nil and unsigned_max_point_summary.rows[1][3] == 'new_planner')
unsigned_max_point = box.execute([[SELECT v FROM planner_preflight_unsigned_t WHERE id = 18446744073709551615]])
assert(#unsigned_max_point.rows == 1 and unsigned_max_point.rows[1][1] == 10)
unsigned_negative_summary, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_unsigned_t WHERE id = -1]])
assert(err == nil and unsigned_negative_summary.rows[1][3] == 'fallback')
unsigned_negative_point = box.execute([[SELECT v FROM planner_preflight_unsigned_t WHERE id = -1]])
assert(#unsigned_negative_point.rows == 0)
box.execute([[DROP TABLE planner_preflight_unsigned_t]])

box.execute([[SET SESSION "sql_new_planner_single_table" = false]])
summary, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_t]])
assert(err == nil and summary.rows[1][3] == 'fallback')
point_disabled_summary, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM planner_preflight_t WHERE id = 2]])
assert(err == nil and point_disabled_summary.rows[1][3] == 'fallback')

box.execute([[DROP TABLE planner_preflight_t]])
test_run = require('test_run').new()
