test_run = require('test_run').new()
engine = test_run:get_cfg('engine')
_ = box.space._session_settings:update('sql_default_engine', {{'=', 2, engine}})

box.execute([[CREATE TABLE fallback_expression_t (id INTEGER PRIMARY KEY, v STRING)]])
before = box.stat.sql()
cast_summary, err = box.execute([[EXPLAIN (planner = 'summary') SELECT CAST(v AS INTEGER) FROM fallback_expression_t]])
assert(err == nil)
assert(cast_summary.rows[1][3] == 'fallback')
assert(cast_summary.rows[2][3] == 'UNSUPPORTED_EXPRESSION')
like_summary, err = box.execute([[EXPLAIN (planner = 'summary') SELECT v FROM fallback_expression_t WHERE v LIKE '%x%']])
assert(err == nil)
assert(like_summary.rows[2][3] == 'UNSUPPORTED_EXPRESSION')
after = box.stat.sql()
assert(after.sql_planner_fallback_total == before.sql_planner_fallback_total + 2)
assert(after.sql_planner_fallback_UNSUPPORTED_EXPRESSION_total == before.sql_planner_fallback_UNSUPPORTED_EXPRESSION_total + 2)
test_run = require('test_run').new()
