#!/usr/bin/env python3
"""
Generate sorter compare fragments for Copy-and-Patch stitching.

Each emitted function is one key-part fragment template. Clang compiles these
to preserve-none code once at build time, and the runtime sorter stitcher later
copies those bytes and patches the helper/next/fallback relocations.
"""

import argparse


FRAGMENTS = [
    {
        "name": "string_asc",
        "helper": "vdbeSorterCompareCnpFieldString",
        "negate": False,
    },
    {
        "name": "string_desc",
        "helper": "vdbeSorterCompareCnpFieldString",
        "negate": True,
    },
    {
        "name": "intlike_asc",
        "helper": "vdbeSorterCompareCnpFieldIntLike",
        "negate": False,
    },
    {
        "name": "intlike_desc",
        "helper": "vdbeSorterCompareCnpFieldIntLike",
        "negate": True,
    },
]


HEADER = """\
/*
 * Auto-generated by tools/vdbe_sorter_cnp_genfrags.py -- DO NOT EDIT.
 */

#include <stdint.h>
#define VDBE_SORTER_CNP_FRAGMENT_BUILD 1
#include "vdbesort_templates.h"

typedef int (*sorter_cnp_frag_exec_func_t)(const char **field1,
					   const char **field2)
	__attribute__((preserve_none));

extern int sorter_cnp_frag_next(const char **field1, const char **field2)
	__attribute__((preserve_none));
extern int sorter_cnp_frag_fallback(const char **field1, const char **field2)
	__attribute__((preserve_none));

#define JMP_NEXT() do {							\\
	__attribute__((musttail)) return sorter_cnp_frag_next(field1, field2);	\\
} while (0)

#define JMP_FALLBACK() do {						\\
	__attribute__((musttail)) return sorter_cnp_frag_fallback(field1, field2); \\
} while (0)

"""


FRAGMENT_TEMPLATE = """\
__attribute__((preserve_none, noinline, used))
int
sorter_cnp_frag_sym_{name}(const char **field1, const char **field2)
{{
	int rc = {helper}(field1, field2);
	if (rc == -2)
		JMP_FALLBACK();
	if (rc != 0) {{
{negate}
		return rc;
	}}
	/* Equal prefix: continue with the next stitched key-part fragment. */
	JMP_NEXT();
}}

"""


def render_fragment(spec):
    negate = "\t\trc = -rc;" if spec["negate"] else ""
    return FRAGMENT_TEMPLATE.format(
        name=spec["name"],
        helper=spec["helper"],
        negate=negate,
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--output", required=True)
    args = ap.parse_args()

    with open(args.output, "w", encoding="utf-8") as f:
        f.write(HEADER)
        for frag in FRAGMENTS:
            f.write(render_fragment(frag))


if __name__ == "__main__":
    main()
