#!/usr/bin/env python3
"""
Generate a dedicated threaded-fragment production source for CnP research.

This is intentionally separate from the shipping wrapper-stencil pipeline.
The generated source compiles a small pilot subset of the threaded dispatcher
into one function with addressable begin/dispatch/end labels so that a future
extractor can recover stitchable opcode fragments without function wrappers.
"""

import argparse
import os


PILOT_FRAGMENTS = [
    {
        "name": "OP_Integer",
        "kind": "CNP_FRAG_FALLTHROUGH",
        "body": """\
if (vdbe_op_integer(p, pOp, aMem))
    GOTO_ERROR();""",
        "dispatch": "DISPATCH();",
    },
    {
        "name": "OP_Bool",
        "kind": "CNP_FRAG_FALLTHROUGH",
        "body": """\
if (vdbe_op_bool(p, pOp, aMem))
    GOTO_ERROR();""",
        "dispatch": "DISPATCH();",
    },
    {
        "name": "OP_Int64",
        "kind": "CNP_FRAG_FALLTHROUGH",
        "body": """\
if (vdbe_op_int64(p, pOp, aMem))
    GOTO_ERROR();""",
        "dispatch": "DISPATCH();",
    },
    {
        "name": "OP_Init",
        "kind": "CNP_FRAG_JUMP_P2",
        "body": "",
        "dispatch": "JUMP_P2();",
    },
    {
        "name": "OP_Add",
        "kind": "CNP_FRAG_FALLTHROUGH",
        "body": """\
if (vdbe_op_add(p, pOp, aMem))
    GOTO_ERROR();""",
        "dispatch": "DISPATCH();",
    },
    {
        "name": "OP_Subtract",
        "kind": "CNP_FRAG_FALLTHROUGH",
        "body": """\
if (vdbe_op_sub(p, pOp, aMem))
    GOTO_ERROR();""",
        "dispatch": "DISPATCH();",
    },
    {
        "name": "OP_Multiply",
        "kind": "CNP_FRAG_FALLTHROUGH",
        "body": """\
if (vdbe_op_multiply(p, pOp, aMem))
    GOTO_ERROR();""",
        "dispatch": "DISPATCH();",
    },
    {
        "name": "OP_Divide",
        "kind": "CNP_FRAG_FALLTHROUGH",
        "body": """\
if (vdbe_op_divide(p, pOp, aMem))
    GOTO_ERROR();""",
        "dispatch": "DISPATCH();",
    },
    {
        "name": "OP_Remainder",
        "kind": "CNP_FRAG_FALLTHROUGH",
        "body": """\
if (vdbe_op_remainder(p, pOp, aMem))
    GOTO_ERROR();""",
        "dispatch": "DISPATCH();",
    },
    {
        "name": "OP_Goto",
        "kind": "CNP_FRAG_JUMP_P2",
        "body": "",
        "dispatch": "JUMP_P2();",
    },
    {
        "name": "OP_IfNot",
        "kind": "CNP_FRAG_JUMP_P2",
        "body": """\
{
    int handler_rc = vdbe_op_ifnot_inline(p, pOp, aMem);
    if (handler_rc < 0)
        GOTO_ERROR();
    if (handler_rc == 1)
        JUMP_P2();
}""",
        "dispatch": "DISPATCH();",
    },
    {
        "name": "OP_Once",
        "kind": "CNP_FRAG_JUMP_P2",
        "body": """\
{
    int handler_rc = vdbe_op_once_inline(p, pOp, aMem);
    if (handler_rc < 0)
        GOTO_ERROR();
    if (handler_rc == 1)
        JUMP_P2();
}""",
        "dispatch": "DISPATCH();",
    },
    {
        "name": "OP_Halt",
        "kind": "CNP_FRAG_TERMINAL",
        "body": "",
        "dispatch": "GOTO_DONE();",
    },
    {
        "name": "OP_ResultRow",
        "kind": "CNP_FRAG_ROW",
        "body": """\
{
    int handler_rc = vdbe_op_resultrow(p, pOp, aMem);
    if (handler_rc < 0)
        GOTO_ERROR();
    if (handler_rc == 1)
        GOTO_ROW();
}""",
        "dispatch": "DISPATCH();",
    },
]


HEADER = """\
/*
 * Auto-generated by tools/vdbe_cnp_genfrags.py — DO NOT EDIT
 *
 * Dedicated threaded fragment source for Copy-and-Patch extraction research.
 * This is not a production dispatcher. Its job is to compile stitchable
 * opcode fragments with explicit begin/dispatch/end labels.
 */

#include <stddef.h>
#include "sqlInt.h"
#include "vdbeInt.h"
#include "vdbe.h"
#include "vdbe_ops.h"

enum cnp_fragment_kind {
    CNP_FRAG_NONE = 0,
    CNP_FRAG_FALLTHROUGH = 1,
    CNP_FRAG_JUMP_P2 = 2,
    CNP_FRAG_ROW = 3,
    CNP_FRAG_TERMINAL = 4,
};

struct cnp_fragment_entry {
    int opcode;
    uint32_t begin_offset;
    uint32_t dispatch_offset;
    uint32_t end_offset;
    int kind;
};

extern struct Vdbe *cnp_frag_get_p(void);
extern VdbeOp *cnp_frag_get_aOp(void);
extern VdbeOp *cnp_frag_get_pOp(void);
extern Mem *cnp_frag_get_aMem(void);
extern void cnp_frag_get_p_pOp_aMem(struct Vdbe **pp, VdbeOp **ppOp, Mem **paMem);
extern void **cnp_frag_get_dispatch_table(void);
extern void *cnp_frag_get_error_target(void);
extern void *cnp_frag_get_row_target(void);
extern void *cnp_frag_get_done_target(void);
extern void *cnp_frag_dispatch_fallthrough(void);
extern void *cnp_frag_dispatch_jump_p2(void);
static volatile int cnp_fragment_probe_opcode = -1;

#if defined(__clang__)
__attribute__((noinline, optnone, used))
#else
__attribute__((noinline, used))
#endif
const struct cnp_fragment_entry *
cnp_fragment_entries(size_t *count)
{
#define p cnp_frag_get_p()
#define aOp cnp_frag_get_aOp()
#define pOp cnp_frag_get_pOp()
#define aMem cnp_frag_get_aMem()
#define P1 pOp->p1
#define P2 pOp->p2
#define P3 pOp->p3

"""

FOOTER = """\
    static const struct cnp_fragment_entry entries[] = {
__ENTRIES__
    };

    if (count != NULL)
        *count = sizeof(entries) / sizeof(entries[0]);

__PROBE_CASES__
    return entries;

cnp_fragment_base:
    __asm__ __volatile__(".globl cnp_frag_base_label\\n\\t"
                         "cnp_frag_base_label:");

#define DISPATCH() do {                                        \\
    void *__disp_t = cnp_frag_dispatch_fallthrough();          \\
    __asm__ volatile ("jmpq *%0" :: "r"(__disp_t));            \\
} while (0)

#define JUMP_P2() do {                                         \\
    void *__disp_t = cnp_frag_dispatch_jump_p2();              \\
    __asm__ volatile ("jmpq *%0" :: "r"(__disp_t));            \\
} while (0)

#define GOTO_ERROR() do {                                      \\
    void *__disp_t = cnp_frag_get_error_target();              \\
    __asm__ volatile ("jmpq *%0" :: "r"(__disp_t));            \\
} while (0)

#define GOTO_ROW() do {                                        \\
    void *__disp_t = cnp_frag_get_row_target();                \\
    __asm__ volatile ("jmpq *%0" :: "r"(__disp_t));            \\
} while (0)

#define GOTO_DONE() do {                                       \\
    void *__disp_t = cnp_frag_get_done_target();               \\
    __asm__ volatile ("jmpq *%0" :: "r"(__disp_t));            \\
} while (0)

__LABELS__

#undef GOTO_DONE
#undef GOTO_ROW
#undef GOTO_ERROR
#undef JUMP_P2
#undef DISPATCH
#undef P3
#undef P2
#undef P1
#undef aMem
#undef pOp
#undef aOp
#undef p
}
"""


def generate(output_path: str) -> None:
    entry_lines = []
    for frag in PILOT_FRAGMENTS:
        entry_lines.append(
            "        { %s, "
            "(uint32_t)((uintptr_t)&&%s_begin - (uintptr_t)&&cnp_fragment_base), "
            "(uint32_t)((uintptr_t)&&%s_dispatch - (uintptr_t)&&cnp_fragment_base), "
            "(uint32_t)((uintptr_t)&&%s_end - (uintptr_t)&&cnp_fragment_base), %s },"
            % (frag["name"], frag["name"], frag["name"], frag["name"],
               frag["kind"])
        )

    probe_cases = []
    for frag in PILOT_FRAGMENTS:
        probe_cases.append(
            f"    if (cnp_fragment_probe_opcode == {frag['name']}) "
            f"goto {frag['name']}_begin;"
        )

    label_blocks = []
    for frag in PILOT_FRAGMENTS:
        body = frag["body"]
        body_block = ""
        if body:
            body_block = "    " + body.replace("\n", "\n    ") + "\n"
        label_blocks.append(
            f"""{frag["name"]}_begin:
{body_block}{frag["name"]}_dispatch:
    {frag["dispatch"]}
{frag["name"]}_end:
    __asm__ volatile("" ::: "memory");
"""
        )

    text = HEADER
    text += FOOTER.replace("__ENTRIES__", "\n".join(entry_lines)).replace(
        "__LABELS__", "\n".join(label_blocks)
    ).replace(
        "__PROBE_CASES__", "\n".join(probe_cases)
    )

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(text)

    print(f"Generated {output_path} with {len(PILOT_FRAGMENTS)} fragment entries")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate a dedicated threaded fragment source for CnP"
    )
    parser.add_argument("--output", required=True, help="Output C file path")
    args = parser.parse_args()
    generate(args.output)


if __name__ == "__main__":
    main()
