#!/usr/bin/env python3
"""
Copy-and-Patch stencil stub generator.

Reads tools/vdbe_dsl/opcodes.yaml and generates vdbe_cnp_stubs.c — one wrapper
function per opcode that uses HOLE_* extern symbols to create relocations the
stencil extractor can later find and classify.

For M1, generate stubs for 5 opcodes only: OP_Integer, OP_Add, OP_Copy,
OP_Goto, OP_ResultRow.

Strategy: Each stencil is a function taking (Vdbe *p, Mem *aMem) that returns
an int (next stencil address or special code).  The CnP runtime loops:
  while ((rc = stencil(p, aMem)) > 0) { stencil = (func_t)rc; }
  return rc;  // 0 = done, negative = error, SQL_ROW, SQL_DONE

This avoids the stack-leak problem entirely — each stencil is a normal
function call with proper prologue/epilogue.
"""

import argparse
import os
import sys
import yaml

M1_OPCODES = {"OP_Integer", "OP_Add", "OP_Copy", "OP_Goto", "OP_ResultRow",
              "OP_Halt", "OP_Init"}

HEADER = """\
/*
 * Auto-generated by tools/vdbe_cnp_genstubs.py — DO NOT EDIT
 *
 * Copy-and-Patch stencil wrappers.  Each function returns the address
 * of the next stencil to execute, or a special status code.
 */

#include <stdint.h>
#include <stddef.h>

/*
 * Hole markers — extern symbols whose relocations become "holes"
 * in the extracted stencils.
 *
 * Operand holes (P1..P5) generate R_X86_64_32S relocations (32-bit
 * signed immediate) when used as integer initializers.
 *
 * Control-flow and handler holes (NEXT, BRANCH, ERROR_EXIT, HANDLER)
 * use LOAD_HOLE() which emits a movabs + R_X86_64_64 relocation,
 * giving a full 64-bit patchable immediate that works at any address.
 */
extern uint64_t HOLE_P1;
extern uint64_t HOLE_P2;
extern uint64_t HOLE_P3;
extern uint64_t HOLE_P4;
extern uint64_t HOLE_P5;
extern uint64_t HOLE_NEXT;
extern uint64_t HOLE_BRANCH;
extern uint64_t HOLE_ERROR_EXIT;
/*
 * HOLE_HANDLER: 64-bit absolute address of the opcode handler function.
 * Loaded via movabs so the relocation is R_X86_64_64 (no ±2 GB limit),
 * allowing the JIT buffer to be mapped at any address.
 */
extern uint64_t HOLE_HANDLER;
/*
 * HOLE_SIGNAL: address of cnp_signal_row(); called by OP_ResultRow to
 * notify the dispatch loop that a result row is ready.
 */
extern uint64_t HOLE_SIGNAL;

/*
 * Load a 64-bit HOLE address via movabs.  Produces a 10-byte instruction
 * with an R_X86_64_64 relocation — a full 64-bit patchable immediate.
 */
static __attribute__((always_inline)) inline uint64_t
cnp_load_hole(uint64_t *hole)
{
    uint64_t val;
    __asm__ volatile("movabs %1, %0" : "=r"(val) : "i"(hole));
    return val;
}

#define LOAD_HOLE(name) cnp_load_hole(&(name))

/* Forward declarations — real types from Tarantool. */
struct Vdbe;
struct VdbeOp;
struct Mem;

typedef struct Mem Mem;

/*
 * Minimal Op struct matching the beginning of VdbeOp.
 * Used to pass operands to external handler functions.
 */
struct CnpOp {
    uint8_t opcode;
    uint8_t p4type;
    uint16_t p5;
    int p1;
    int p2;
    int p3;
};

/*
 * Stencil return convention:
 *   >= CNP_ADDR_THRESHOLD : address of next stencil (int64_t cast)
 *   SQL_DONE (2)          : all rows delivered
 *   SQL_ROW  (1)          : row ready (caller must resume)
 *   -1                    : fatal error
 *
 * Valid mmap'd addresses on x86_64 Linux are always well above 4096,
 * so small integers are safe as status codes.
 */

"""


def emit_external_handler(name, handler_func, branch_type):
    """Emit a stub that calls an external handler and returns next address.

    Uses LOAD_HOLE(HOLE_HANDLER) for the call so the relocation is an
    R_X86_64_64 (64-bit absolute movabs), which works at any JIT buffer
    address — unlike a PLT32 call that only covers ±2 GB.

    branch_type:
      "none" — always falls through to HOLE_NEXT
      "jump" — on rc>0, returns HOLE_BRANCH (e.g. OP_Init jumps to P2)
      "row"  — on rc>0, calls HOLE_SIGNAL(p) to set cnp_row_ready,
               then returns HOLE_NEXT (e.g. OP_ResultRow)
    """
    lines = []
    lines.append("typedef int (*cnp_handler_fn_t)"
                 "(struct Vdbe *, struct VdbeOp *, Mem *);")
    lines.append(f"int64_t __attribute__((noinline))")
    lines.append(f"cnp_{name}(struct Vdbe *p, Mem *aMem)")
    lines.append("{")
    lines.append("    struct CnpOp op = {")
    lines.append("        .p1 = (int)(uint64_t)&HOLE_P1,")
    lines.append("        .p2 = (int)(uint64_t)&HOLE_P2,")
    lines.append("        .p3 = (int)(uint64_t)&HOLE_P3,")
    lines.append("        .p5 = (uint16_t)(uint64_t)&HOLE_P5,")
    lines.append("    };")
    lines.append("    cnp_handler_fn_t fn =")
    lines.append("        (cnp_handler_fn_t)(uintptr_t)LOAD_HOLE(HOLE_HANDLER);")
    lines.append(f"    int rc = fn(p, (struct VdbeOp *)&op, aMem);")
    lines.append("    if (rc < 0)")
    lines.append("        return (int64_t)LOAD_HOLE(HOLE_ERROR_EXIT);")
    if branch_type == "jump":
        lines.append("    if (rc > 0)")
        lines.append("        return (int64_t)LOAD_HOLE(HOLE_BRANCH);")
    elif branch_type == "row":
        lines.append("    if (rc > 0) {")
        lines.append("        typedef void (*cnp_signal_fn_t)(struct Vdbe *);")
        lines.append("        cnp_signal_fn_t sig =")
        lines.append("            (cnp_signal_fn_t)(uintptr_t)LOAD_HOLE(HOLE_SIGNAL);")
        lines.append("        sig(p);")
        lines.append("    }")
    lines.append("    return (int64_t)LOAD_HOLE(HOLE_NEXT);")
    lines.append("}")
    return "\n".join(lines)


def emit_goto_stub():
    """OP_Goto: unconditional jump to P2."""
    return """\
int64_t __attribute__((noinline))
cnp_OP_Goto(struct Vdbe *p, Mem *aMem)
{
    (void)p; (void)aMem;
    return (int64_t)LOAD_HOLE(HOLE_BRANCH);
}"""


def generate(yaml_path, output_path):
    with open(yaml_path, "r") as f:
        opcodes = yaml.safe_load(f)

    opcode_map = {op["name"]: op for op in opcodes}

    with open(output_path, "w") as out:
        out.write(HEADER)

        out.write("/* --- OP_Goto (control_flow: unconditional jump) --- */\n")
        out.write(emit_goto_stub())
        out.write("\n\n")

        out.write("/* --- OP_Init (external, jump to P2 on success) --- */\n")
        out.write(emit_external_handler("OP_Init", "vdbe_cnp_init_handler",
                                         "jump"))
        out.write("\n\n")

        out.write("/* --- OP_Halt (external, jump branch returns SQL_DONE) --- */\n")
        out.write(emit_external_handler("OP_Halt", "vdbe_cnp_halt_handler",
                                         "jump"))
        out.write("\n\n")

        out.write("/* --- OP_Integer (external, no branch) --- */\n")
        out.write(emit_external_handler("OP_Integer", "vdbe_op_integer",
                                         "none"))
        out.write("\n\n")

        out.write("/* --- OP_Add (external, no branch) --- */\n")
        out.write(emit_external_handler("OP_Add", "vdbe_op_add", "none"))
        out.write("\n\n")

        out.write("/* --- OP_Copy (external, no branch) --- */\n")
        out.write(emit_external_handler("OP_Copy", "vdbe_op_copy", "none"))
        out.write("\n\n")

        out.write("/* --- OP_ResultRow (external, signal row then continue) --- */\n")
        out.write(emit_external_handler("OP_ResultRow",
                                         "vdbe_op_resultrow", "row"))
        out.write("\n")

    print(f"Generated {output_path} with {len(M1_OPCODES)} stencil stubs")


def main():
    parser = argparse.ArgumentParser(
        description="Generate CnP stencil stubs from opcodes.yaml"
    )
    parser.add_argument(
        "--yaml",
        default=os.path.join(os.path.dirname(__file__), "vdbe_dsl",
                             "opcodes.yaml"),
        help="Path to opcodes.yaml",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Output C file path",
    )
    args = parser.parse_args()
    generate(args.yaml, args.output)


if __name__ == "__main__":
    main()
