#!/usr/bin/env python3
"""
Generate sorter writer fragments for Copy-and-Patch stitching.

Each emitted function is one writer-part fragment template. Clang compiles
these to preserve-none code once at build time, and the runtime writer stitcher
later copies those bytes and patches the helper/next/fallback relocations.
"""

import argparse


FRAGMENTS = [
    {
        "name": "measure_string",
        "body": """\
\tconst struct Mem *mem = state->mem;
\tif (!mem_is_str(mem) || mem_is_metatype(mem))
\t\tJMP_FALLBACK();
\tstate->total += mp_sizeof_str((uint32_t)mem->n);
\tstate->mem = mem + 1;
""",
    },
    {
        "name": "measure_intlike",
        "body": """\
\tconst struct Mem *mem = state->mem;
\tif (mem->type == MEM_TYPE_INT) {
\t\tstate->total += mp_sizeof_int(mem->u.i);
\t\tstate->mem = mem + 1;
\t} else if (mem->type == MEM_TYPE_UINT) {
\t\tstate->total += mp_sizeof_uint(mem->u.u);
\t\tstate->mem = mem + 1;
\t} else {
\t\tJMP_FALLBACK();
\t}
""",
    },
    {
        "name": "encode_string",
        "body": """\
\tconst struct Mem *mem = state->mem;
\tif (!mem_is_str(mem) || mem_is_metatype(mem))
\t\tJMP_FALLBACK();
\tstate->pos = mp_encode_str(state->pos, mem->z, (uint32_t)mem->n);
\tstate->mem = mem + 1;
""",
    },
    {
        "name": "encode_intlike",
        "body": """\
\tconst struct Mem *mem = state->mem;
\tif (mem->type == MEM_TYPE_INT) {
\t\tstate->pos = mp_encode_int(state->pos, mem->u.i);
\t\tstate->mem = mem + 1;
\t} else if (mem->type == MEM_TYPE_UINT) {
\t\tstate->pos = mp_encode_uint(state->pos, mem->u.u);
\t\tstate->mem = mem + 1;
\t} else {
\t\tJMP_FALLBACK();
\t}
""",
    },
]


HEADER = """\
/*
 * Auto-generated by tools/vdbe_sorter_writer_cnp_genfrags.py -- DO NOT EDIT.
 */

#include <stdint.h>
#define VDBE_SORTER_CNP_FRAGMENT_BUILD 1
#include "vdbesort_templates.h"
#include "sqlInt.h"
#include "mem.h"
#include "msgpuck.h"

typedef int (*sorter_writer_cnp_frag_exec_func_t)(
	struct vdbe_sorter_cnp_write_state *state)
	__attribute__((preserve_none));

extern int
sorter_writer_cnp_frag_next(struct vdbe_sorter_cnp_write_state *state)
	__attribute__((preserve_none));
extern int
sorter_writer_cnp_frag_fallback(struct vdbe_sorter_cnp_write_state *state)
	__attribute__((preserve_none));

#define JMP_NEXT() do {							\\
	__attribute__((musttail)) return sorter_writer_cnp_frag_next(state);	\\
} while (0)

#define JMP_FALLBACK() do {						\\
	__attribute__((musttail)) return sorter_writer_cnp_frag_fallback(state); \\
} while (0)

"""


FRAGMENT_TEMPLATE = """\
__attribute__((preserve_none, noinline, used))
int
sorter_writer_cnp_frag_sym_{name}(struct vdbe_sorter_cnp_write_state *state)
{{
{body}\
	JMP_NEXT();
}}

"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--output", required=True)
    args = ap.parse_args()

    with open(args.output, "w", encoding="utf-8") as f:
        f.write(HEADER)
        for frag in FRAGMENTS:
            f.write(FRAGMENT_TEMPLATE.format(**frag))


if __name__ == "__main__":
    main()
