#!/usr/bin/env python3
"""
vdbe_codegen.py

Simple generator that reads a YAML (or JSON) opcode spec and emits two files:
- a header `vdbe_opcodes_generated.h` with enum and properties
- a C dispatch skeleton `vdbe_dispatch_generated.c`

Usage:
  python3 tools/vdbe_codegen.py --in tools/vdbe_dsl/opcodes.yaml --out src/box/sql/generated

This script prefers PyYAML if available; otherwise it accepts JSON input.
"""
import os
import sys
import argparse
import json

try:
    import yaml
    _HAS_YAML = True
except Exception:
    _HAS_YAML = False

FLAG_BITS = {
    'IN1': 0x0001,
    'IN2': 0x0002,
    'OUT2': 0x0004,
    'JUMP': 0x0008,
    'OUT3': 0x0010,
}


def load_spec(path):
    with open(path, 'r') as f:
        text = f.read()
    if path.endswith('.json'):
        return json.loads(text)
    if _HAS_YAML:
        return yaml.safe_load(text)
    # Try a very small YAML-ish fallback for simple sequences
    try:
        return json.loads(text)
    except Exception:
        raise RuntimeError('YAML support missing; install PyYAML or provide JSON input')


def assign_ids(opcodes):
    next_id = 0
    for op in opcodes:
        if 'id' in op and op['id'] is not None:
            next_id = op['id'] + 1
        else:
            while any(o.get('id') == next_id for o in opcodes):
                next_id += 1
            op['id'] = next_id
            next_id += 1


def gen_header(opcodes):
    lines = []
    lines.append('/* Generated by tools/vdbe_codegen.py - do not edit */')
    lines.append('#ifndef VDBE_OPCODES_GENERATED_H')
    lines.append('#define VDBE_OPCODES_GENERATED_H')
    lines.append('\n#ifdef __cplusplus')
    lines.append('extern "C" {')
    lines.append('#endif\n')

    lines.append('/* Forward declarations */')
    lines.append('struct Vdbe; struct Op; struct Mem;')

    lines.append('/* Opcode enum (namespaced to avoid conflicts) */')
    lines.append('typedef enum {')
    for op in opcodes:
        # Normalize name: strip leading "OP_" if present, then namespace
        raw = op['name']
        base = raw
        if raw.startswith('OP_'):
            base = raw[3:]
        base = base.upper()
        lines.append('    VDBE_OP_%s = %d,' % (base, op['id']))
    lines.append('} VdbeOpcode;\n')

    lines.append('/* Opcode property flags */')
    for name, bit in FLAG_BITS.items():
        lines.append('#define VDBE_OPFLG_%s 0x%04x' % (name, bit))
    lines.append('\n/* Property table */')
    lines.append('static const unsigned short vdbeOpcodeProperty[] = {')
    # build a table indexed by opcode id; fill missing ids with 0
    max_id = max(op['id'] for op in opcodes)
    prop_by_id = {op['id']: sum(FLAG_BITS.get(f, 0) for f in op.get('flags', [])) for op in opcodes}
    for i in range(0, max_id + 1):
        lines.append('    0x%04x,' % prop_by_id.get(i, 0))
    lines.append('};\n')

    lines.append('/* Handler prototypes (implementations live in vdbe_ops_*.c) */')
    for op in opcodes:
        lname = op['name'].lower().replace('op_', '')
        lines.append('int vdbe_op_%s(struct Vdbe *p, struct Op *pOp, struct Mem *aMem);' % lname)

    lines.append('\n#ifdef __cplusplus')
    lines.append('}')
    lines.append('#endif')
    lines.append('#endif /* VDBE_OPCODES_GENERATED_H */')
    return '\n'.join(lines)


def gen_dispatch_c(opcodes, header_name='vdbe_opcodes_generated.h'):
    lines = []
    lines.append('/* Generated dispatch skeleton */')
    lines.append('#include "%s"' % header_name)
    lines.append('#include <stddef.h>')
    lines.append('\nstruct VdbeDispatch {')
    lines.append('    int opcode;')
    lines.append('    int (*handler)(struct Vdbe*, struct Op*, struct Mem*);')
    lines.append('    unsigned short flags;')
    lines.append('};\n')

    lines.append('static const struct VdbeDispatch vdbe_dispatch_table[] = {')
    for op in opcodes:
            raw = op['name']
            base = raw
            if raw.startswith('OP_'):
                base = raw[3:]
            base = base.upper()
            lines.append('    { VDBE_OP_%s, vdbe_op_%s, 0x%04x }, /* %s */' % (
                base, op['name'].lower().replace('op_', ''), sum(FLAG_BITS.get(f, 0) for f in op.get('flags', [])), op.get('doc', '')))
    lines.append('};\n')

    lines.append('/* Number of entries */')
    lines.append('const size_t vdbe_dispatch_table_len = sizeof(vdbe_dispatch_table)/sizeof(vdbe_dispatch_table[0]);')
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description='Generate VDBE opcode headers and dispatch from DSL')
    parser.add_argument('--in', dest='infile', required=True, help='Input DSL file (yaml or json)')
    parser.add_argument('--out', dest='outdir', required=True, help='Output directory for generated files')
    args = parser.parse_args()

    infile = args.infile
    outdir = args.outdir
    if not os.path.exists(outdir):
        os.makedirs(outdir)

    spec = load_spec(infile)
    if not isinstance(spec, list):
        raise RuntimeError('Spec must be a top-level list of opcodes')

    assign_ids(spec)

    header = gen_header(spec)
    dispatch = gen_dispatch_c(spec)

    header_path = os.path.join(outdir, 'vdbe_opcodes_generated.h')
    dispatch_path = os.path.join(outdir, 'vdbe_dispatch_generated.c')

    with open(header_path, 'w') as f:
        f.write(header)

    with open(dispatch_path, 'w') as f:
        f.write(dispatch)

    print('Wrote:', header_path)
    print('Wrote:', dispatch_path)


if __name__ == '__main__':
    main()
