#!/usr/bin/env python3
"""
Extract sorter writer fragment metadata from vdbe_sorter_writer_cnp_fragments.o.
"""

import argparse

from elftools.elf.elffile import ELFFile
from elftools.elf.relocation import RelocationSection


FRAGMENT_ORDER = [
    "measure_string",
    "measure_intlike",
    "encode_string",
    "encode_intlike",
]


def c_ident(name):
    return name.replace("-", "_")


def c_string(name):
    return '"' + name.replace("\\", "\\\\").replace('"', '\\"') + '"'


def load_relocations(elf, symtab, target_section_name):
    rels = []
    for section in elf.iter_sections():
        if not isinstance(section, RelocationSection):
            continue
        info_idx = section["sh_info"]
        target = elf.get_section(info_idx)
        if target is None or target.name != target_section_name:
            continue
        for rel in section.iter_relocations():
            sym = symtab.get_symbol(rel["r_info_sym"])
            addend = rel.entry.get("r_addend", 0) if hasattr(rel, "entry") else 0
            rels.append({
                "offset": rel["r_offset"],
                "type": rel["r_info_type"],
                "addend": addend,
                "sym_name": sym.name,
            })
    return rels


def format_bytes(data):
    lines = []
    line = []
    for i, byte in enumerate(data):
        line.append(f"0x{byte:02x}")
        if len(line) == 12 or i == len(data) - 1:
            lines.append("    " + ", ".join(line) + ",")
            line = []
    return "\n".join(lines)


def emit_header(output, fragments):
    with open(output, "w", encoding="utf-8") as f:
        f.write("/*\n")
        f.write(" * Auto-generated by tools/vdbe_sorter_writer_cnp_extract.py.\n")
        f.write(" */\n\n")
        f.write("#ifndef VDBE_SORTER_WRITER_CNP_FRAGMENTS_H\n")
        f.write("#define VDBE_SORTER_WRITER_CNP_FRAGMENTS_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("enum sorter_writer_cnp_fragment_id {\n")
        for idx, name in enumerate(FRAGMENT_ORDER):
            f.write(f"    SORTER_WRITER_CNP_FRAG_{name.upper()} = {idx},\n")
        f.write(f"    SORTER_WRITER_CNP_FRAG_COUNT = {len(FRAGMENT_ORDER)},\n")
        f.write("};\n\n")
        f.write("struct sorter_writer_cnp_fragment_reloc {\n")
        f.write("    uint32_t offset;\n")
        f.write("    uint8_t reloc_type;\n")
        f.write("    int32_t addend;\n")
        f.write("    const char *symbol_name;\n")
        f.write("};\n\n")
        f.write("struct sorter_writer_cnp_fragment {\n")
        f.write("    const uint8_t *bytes;\n")
        f.write("    uint32_t size;\n")
        f.write("    const struct sorter_writer_cnp_fragment_reloc *relocs;\n")
        f.write("    uint32_t num_relocs;\n")
        f.write("};\n\n")
        for name in FRAGMENT_ORDER:
            frag = fragments[name]
            ident = c_ident(name)
            f.write(f"static const uint8_t sorter_writer_cnp_fragment_bytes_{ident}[] = {{\n")
            f.write(format_bytes(frag['bytes']))
            f.write("\n};\n\n")
            f.write(
                f"static const struct sorter_writer_cnp_fragment_reloc "
                f"sorter_writer_cnp_fragment_relocs_{ident}[] = {{\n"
            )
            for rel in frag["relocs"]:
                f.write(
                    "    { .offset = %d, .reloc_type = %d, .addend = %d, "
                    ".symbol_name = %s },\n" %
                    (rel["offset"], rel["type"], rel["addend"],
                     c_string(rel["sym_name"]))
                )
            f.write("};\n\n")
        f.write("static const struct sorter_writer_cnp_fragment sorter_writer_cnp_fragments[] = {\n")
        for name in FRAGMENT_ORDER:
            ident = c_ident(name)
            f.write(
                "    { .bytes = sorter_writer_cnp_fragment_bytes_%s, .size = "
                "(uint32_t)sizeof(sorter_writer_cnp_fragment_bytes_%s), .relocs = "
                "sorter_writer_cnp_fragment_relocs_%s, .num_relocs = (uint32_t)"
                "(sizeof(sorter_writer_cnp_fragment_relocs_%s) / "
                "sizeof(sorter_writer_cnp_fragment_relocs_%s[0])) },\n" %
                (ident, ident, ident, ident, ident)
            )
        f.write("};\n\n")
        f.write("#endif\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", required=True)
    ap.add_argument("--output", required=True)
    args = ap.parse_args()

    with open(args.input, "rb") as obj:
        elf = ELFFile(obj)
        symtab = elf.get_section_by_name(".symtab")
        fragments = {}
        for name in FRAGMENT_ORDER:
            sym_name = f"sorter_writer_cnp_frag_sym_{name}"
            sym = symtab.get_symbol_by_name(sym_name)
            if not sym:
                raise RuntimeError(f"missing symbol {sym_name}")
            sym = sym[0]
            text_section = elf.get_section(sym["st_shndx"])
            if text_section is None:
                raise RuntimeError(f"missing section for {sym_name}")
            text = text_section.data()
            section_base = text_section["sh_addr"]
            start = sym["st_value"]
            size = sym["st_size"]
            rels = load_relocations(elf, symtab, text_section.name)
            frag_rels = []
            for rel in rels:
                if start <= rel["offset"] < start + size:
                    frag_rels.append({
                        "offset": rel["offset"] - start,
                        "type": rel["type"],
                        "addend": rel["addend"],
                        "sym_name": rel["sym_name"],
                    })
            fragments[name] = {
                "bytes": text[start - section_base:start - section_base + size],
                "relocs": frag_rels,
            }
    emit_header(args.output, fragments)


if __name__ == "__main__":
    main()
