#!/usr/bin/env python3
"""
vdbe_codegen.py

Generator that reads a YAML (or JSON) opcode spec and emits:
- a header `vdbe_opcodes_generated.h` with enum and properties
- a C dispatch loop `vdbe_dispatch_generated.c` with complete execution dispatcher

Usage:
  python3 tools/vdbe_codegen.py --in tools/vdbe_dsl/opcodes.yaml --out src/box/sql/generated

This script prefers PyYAML if available; otherwise it accepts JSON input.

Features:
  - Generates enum with opcode IDs
  - Creates handler prototypes for external handlers
  - Generates complete dispatch loop (both computed-goto and switch modes)
  - Supports handler types: external, inline, fallthrough, control_flow
  - Preserves return value handling for special cases (jumps, SQL_ROW, etc.)
"""
import os
import sys
import argparse
import json

try:
    import yaml
    _HAS_YAML = True
except Exception:
    _HAS_YAML = False

FLAG_BITS = {
    'IN1': 0x0001,
    'IN2': 0x0002,
    'OUT2': 0x0004,
    'JUMP': 0x0008,
    'OUT3': 0x0010,
}

# Handler types and their dispatch strategy
HANDLER_TYPES = {
    'external': 'Call external handler function',
    'inline': 'Inline opcode implementation',
    'fallthrough': 'Shared fallthrough case (no break)',
    'control_flow': 'Control flow operation (deferred to Phase 6)',
}


def load_spec(path):
    with open(path, 'r') as f:
        text = f.read()
    if path.endswith('.json'):
        return json.loads(text)
    if _HAS_YAML:
        return yaml.safe_load(text)
    # Try a very small YAML-ish fallback for simple sequences
    try:
        return json.loads(text)
    except Exception:
        raise RuntimeError('YAML support missing; install PyYAML or provide JSON input')


def assign_ids(opcodes):
    next_id = 0
    for op in opcodes:
        if 'id' in op and op['id'] is not None:
            next_id = op['id'] + 1
        else:
            while any(o.get('id') == next_id for o in opcodes):
                next_id += 1
            op['id'] = next_id
            next_id += 1


def gen_header(opcodes):
    lines = []
    lines.append('/* Generated by tools/vdbe_codegen.py - do not edit */')
    lines.append('#ifndef VDBE_OPCODES_GENERATED_H')
    lines.append('#define VDBE_OPCODES_GENERATED_H')
    lines.append('\n#ifdef __cplusplus')
    lines.append('extern "C" {')
    lines.append('#endif\n')

    lines.append('/* Forward declarations */')
    lines.append('struct Vdbe; struct Op; struct Mem;')

    lines.append('/* Opcode enum (namespaced to avoid conflicts) */')
    lines.append('typedef enum {')
    for op in opcodes:
        # Normalize name: strip leading "OP_" if present, then namespace
        raw = op['name']
        base = raw
        if raw.startswith('OP_'):
            base = raw[3:]
        base = base.upper()
        lines.append('    VDBE_OP_%s = %d,' % (base, op['id']))
    lines.append('} VdbeOpcode;\n')

    lines.append('/* Opcode property flags */')
    for name, bit in FLAG_BITS.items():
        lines.append('#define VDBE_OPFLG_%s 0x%04x' % (name, bit))
    lines.append('\n/* Property table */')
    lines.append('static const unsigned short vdbeOpcodeProperty[] = {')
    # build a table indexed by opcode id; fill missing ids with 0
    max_id = max(op['id'] for op in opcodes)
    prop_by_id = {op['id']: sum(FLAG_BITS.get(f, 0) for f in op.get('flags', [])) for op in opcodes}
    for i in range(0, max_id + 1):
        lines.append('    0x%04x,' % prop_by_id.get(i, 0))
    lines.append('};\n')

    lines.append('/* Handler prototypes (implementations live in vdbe_ops_*.c) */')
    for op in opcodes:
        lname = op['name'].lower().replace('op_', '')
        lines.append('int vdbe_op_%s(struct Vdbe *p, struct Op *pOp, struct Mem *aMem);' % lname)

    lines.append('\n#ifdef __cplusplus')
    lines.append('}')
    lines.append('#endif')
    lines.append('#endif /* VDBE_OPCODES_GENERATED_H */')
    return '\n'.join(lines)


def get_opcode_name(op):
    """Extract clean opcode name."""
    raw = op['name']
    if raw.startswith('OP_'):
        return raw[3:].upper()
    return raw.upper()


def get_handler_name(op):
    """Extract handler function name."""
    return op['name'].lower().replace('op_', '')


def get_handler_type(op):
    """Get handler type for an opcode (default: external for handlers)."""
    return op.get('handler_type', 'external')


def gen_dispatch_c_goto(opcodes, header_name='vdbe_opcodes_generated.h'):
    """Generate dispatch loop using computed-goto (SQL_USE_GOTO mode)."""
    lines = []
    lines.append('/* Generated dispatch loop - computed-goto version */')
    lines.append('/* This is included as part of sqlVdbeExec() when SQL_USE_GOTO is defined */')
    lines.append('')
    lines.append('/* Dispatch table for computed-goto - indexed by opcode ID */')
    lines.append('static const void * const dispatch_table[] = {')

    # Create a sorted list of opcodes by ID
    sorted_opcodes = sorted(opcodes, key=lambda op: op['id'])
    max_id = max(op['id'] for op in sorted_opcodes)

    # Build table with entries for all IDs (some may be unused)
    for i in range(max_id + 1):
        op_for_id = next((op for op in sorted_opcodes if op['id'] == i), None)
        if op_for_id:
            lines.append('    &&Exec_%s, /* %d */' % (op_for_id['name'], i))
        else:
            lines.append('    &&Exec_OP_Noop, /* %d - unused */' % i)

    lines.append('};')
    lines.append('')
    lines.append('/* Labels for each opcode - used in computed-goto dispatch */')

    for op in opcodes:
        handler_type = get_handler_type(op)
        handler_name = get_handler_name(op)
        opname = get_opcode_name(op)

        lines.append('Exec_%s: {' % op['name'])
        lines.append('    /* Opcode: %s - %s */' % (opname, op.get('doc', '')))

        if handler_type == 'external':
            lines.append('    int handler_rc = vdbe_op_%s(p, pOp, aMem);' % handler_name)
            lines.append('    if (handler_rc < 0)')
            lines.append('        goto abort_due_to_error;')
            lines.append('    if (handler_rc == 1) {')
            lines.append('        /* Special return value handling (jump or SQL_ROW) */')
            lines.append('        if (pOp->opcode == OP_ResultRow)')
            lines.append('            goto done_returning_row;')
            lines.append('        /* For comparison ops, jump to P2 */')
            lines.append('        JUMP_P2();')
            lines.append('    }')
        elif handler_type == 'inline':
            inline_code = op.get('inline_code', '')
            if inline_code:
                lines.append('    ' + inline_code)
            else:
                lines.append('    /* TODO: Inline code for %s */' % op['name'])
        elif handler_type == 'control_flow':
            lines.append('    /* Control flow op (Phase 6): %s */' % op['name'])

        lines.append('    DISPATCH();')
        lines.append('}')
        lines.append('')

    return '\n'.join(lines)


def gen_dispatch_c_switch(opcodes, header_name='vdbe_opcodes_generated.h'):
    """Generate dispatch loop using switch statement (fallback mode)."""
    lines = []
    lines.append('/* Generated dispatch loop - switch statement version */')
    lines.append('/* This is included as part of sqlVdbeExec() when SQL_USE_GOTO is not defined */')
    lines.append('')
    lines.append('start_eval: switch (pOp->opcode) {')
    lines.append('')

    for op in opcodes:
        handler_type = get_handler_type(op)
        handler_name = get_handler_name(op)
        opname = get_opcode_name(op)

        lines.append('case %s: {' % op['name'])
        lines.append('    /* %s - %s */' % (opname, op.get('doc', '')))

        if handler_type == 'external':
            lines.append('    int handler_rc = vdbe_op_%s(p, pOp, aMem);' % handler_name)
            lines.append('    if (handler_rc < 0)')
            lines.append('        goto abort_due_to_error;')
            lines.append('    if (handler_rc == 1) {')
            lines.append('        if (pOp->opcode == OP_ResultRow)')
            lines.append('            goto done_returning_row;')
            lines.append('        goto jump_to_p2;')
            lines.append('    }')
            lines.append('    break;')
        elif handler_type == 'inline':
            inline_code = op.get('inline_code', '')
            if inline_code:
                lines.append('    ' + inline_code)
            else:
                lines.append('    /* TODO: Inline code for %s */' % op['name'])
            lines.append('    break;')
        elif handler_type == 'control_flow':
            lines.append('    /* Control flow op (Phase 6): %s */' % op['name'])
            lines.append('    break;')

        lines.append('}')
        lines.append('')

    lines.append('} /* end switch */')

    return '\n'.join(lines)


def gen_dispatch_c(opcodes, header_name='vdbe_opcodes_generated.h', use_goto=True):
    """Generate complete dispatch loop with both computed-goto and switch support."""
    lines = []
    lines.append('/* Generated by tools/vdbe_codegen.py - do not edit */')
    lines.append('#include "%s"' % header_name)
    lines.append('')
    lines.append('/*')
    lines.append(' * Complete VDBE dispatch loop generated from opcodes.yaml')
    lines.append(' *')
    lines.append(' * This dispatch replaces the inline EXECUTE() macros in vdbe.c.')
    lines.append(' * It supports both computed-goto (SQL_USE_GOTO) and switch fallback modes.')
    lines.append(' *')
    lines.append(' * External handlers (extracted to vdbe_ops_*.c) are called with:')
    lines.append(' *   int vdbe_op_xxx(Vdbe *p, Op *pOp, Mem *aMem)')
    lines.append(' *')
    lines.append(' * Return values:')
    lines.append(' *   0 = Success, continue to next instruction')
    lines.append(' *  -1 = Error, jump to abort_due_to_error')
    lines.append(' *   1 = Special: comparison ops jump to P2, OP_ResultRow returns SQL_ROW')
    lines.append(' */')
    lines.append('')

    if use_goto:
        lines.append('#ifdef SQL_USE_GOTO')
        lines.append(gen_dispatch_c_goto(opcodes, header_name))
        lines.append('#else /* SQL_USE_GOTO */')
        lines.append(gen_dispatch_c_switch(opcodes, header_name))
        lines.append('#endif /* SQL_USE_GOTO */')
    else:
        lines.append(gen_dispatch_c_switch(opcodes, header_name))

    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description='Generate VDBE opcode headers and dispatch from DSL')
    parser.add_argument('--in', dest='infile', required=True, help='Input DSL file (yaml or json)')
    parser.add_argument('--out', dest='outdir', required=True, help='Output directory for generated files')
    args = parser.parse_args()

    infile = args.infile
    outdir = args.outdir
    if not os.path.exists(outdir):
        os.makedirs(outdir)

    spec = load_spec(infile)
    if not isinstance(spec, list):
        raise RuntimeError('Spec must be a top-level list of opcodes')

    assign_ids(spec)

    header = gen_header(spec)
    dispatch = gen_dispatch_c(spec)

    header_path = os.path.join(outdir, 'vdbe_opcodes_generated.h')
    dispatch_path = os.path.join(outdir, 'vdbe_dispatch_generated.c')

    with open(header_path, 'w') as f:
        f.write(header)

    with open(dispatch_path, 'w') as f:
        f.write(dispatch)

    print('Wrote:', header_path)
    print('Wrote:', dispatch_path)


if __name__ == '__main__':
    main()
